### PR TITLE
Create a dictionary when the parameters type is body and serialize it to JSON.

### PR DESCRIPTION
**Pull request by claudiuolteanu**
This patch fixes the issues reported here [1]. 
Another possible solution is to check the **ParameterType** in the **AddParameter** function of the **Command** class and to do the object serialization there.

Please let me know if you prefere to serialize the object in the Command class.

[1] - https://asternetari.codeplex.com/workitem/1

### CODE REVIEW

**Comment by claudiuolteanu** [comment]
There is style a problem with the content type. I will try to fix it tomorrow.

**Comment by claudiuolteanu** [comment]
there is still*

**Comment by claudiuolteanu** [comment]
Apparently the RestSharp implementation uses the name of the parameter as content type value. Before commit #c0e7380 the HTTP request was:
```
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
User-Agent: RestSharp/104.4.0.0
Content-Type: variables
Host: X.X.X.X:8088
Content-Length: 123
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
```

**Comment by skrusty** [comment]
Can you confirm this is working and tested?

Have just had a quick look through the docs, and it seems all body values are variables, so for the moment your code seems safe enough!

**Comment by claudiuolteanu** [comment]
I only tested the **EventsActions** and it works. If you want I can also test the **Channels** and **Endpoints** actions but I expect them to work as well. Unfortunately there is no description for the **Endpoints.sendMessage** requests but I believe that the format should be the same.

**Comment by skrusty** [comment]
All looks good to me! Will merge, thanks again for your help!

**Comment by claudiuolteanu** [comment]
It was my pleasure. If you need help with other things, please let me know.

**Comment by skrusty** [comment]
Have you checked out the ARI.Middleware project and ARI.Proxy project?

**Comment by claudiuolteanu** [comment]
No, I didn't. As soon I will find some free time I will take a look over them.

**Pull request merged**
