### PR TITLE
Support for async await

### PR DESCRIPTION
**Pull request by seiggy**
Changed the T4 template to generate async classes for Actions.
Fixed T4 generation of the BaseAriClient class (generated class wouldn't compile)
Added new Async Dispatcher for dispatching events using async await, instead of ThreadPooler.

Async/Await should be used instead of Threadpooling as the code we are threading is not CPU bound, but instead network heavy. When threading network code, you should use Async/Await so that other threads can run while waiting on server responses, etc. RestSharp's ExecuteTask and ExecuteTask<T> are used to support the Aync style, instead of the Execute and Execute<T> which are synchronous and blocking.

### CODE REVIEW

**Comment by seiggy** [comment]
Ugh, reject the second commit. I didn't want it to add that to this pull request. Sorry.

**Comment by skrusty** [comment]
Seiggy, great to see a new name contributing!

I will have a look at this later today, but thanks for your contributions.

**Comment by skrusty** [comment]
A few issues I can see with this. Nothing technical but just the implementation pattern. I am no expert in Async/Await, so all being well other members will comment on any specifics of that.

1. This, as it stands breaks AsterNET.ARI. That's bad, as we're trying to confirm to SemVer. All PRs need to be backwards compatible for us to accept them, unless we intent to create a new release with a new major version. Currently I don't think this needs or should warrant that.

2. To deal with issue 1, I personally feel we should implement named Async methods (e.g. SnoopChannel() and SnoopChannelAsync()). Hope that makes sense, it seems to be the most comment API pattern from MS for async/await.

The biggest reason for my comments is that other APIs such as the AsterNET.ARI.Middleware.Queue are dependant on this, and as such, they would be broken!

All being well, others will contribute their thoughts on this too soon. Thanks again!

**Comment by jonastelzio** [comment]
@seiggy Fantastic!

However, as @skrusty says this will break compatibility with previous versions.

All the new methods should be Postfixed with Async, that's generally how microsoft does it as well, and the non async methods should be emitted as well (to maintain backwards compatibility), just calling .Result on the corresponding Async method.

@skrusty we should also drop the RestSharp dependency asap now that this work is being made.

**Comment by skrusty** [comment]
@jonastelzio Agreed! It should be easy to add in a new middleware that uses HttpClient to migrate away!

See: https://github.com/skrusty/AsterNET.ARI/blob/master/AsterNET.ARI/Middleware/Default/Command.cs

**Comment by seiggy** [comment]
Sounds good. I'm at \\build this week, so I'll take a crack at fixing it when I return. Although I'd recommend we use AsyncTask instead of Async to append to the method. All the new async/await methods in the .NET framework use AsyncTask or just Task for method names.

Go ahead and reject this pull request. I'll create a new one with the fixed AsyncTask changes, and see if I can add the HttpClient middleware as well.

**Comment by skrusty** [comment]
You lucky sod!! Wish I was at build.

**Comment by seiggy** [comment]
haha! it's been a blast. Lots of really cool new stuff with their Intelligence API Suite.

**Comment by skrusty** [comment]
@seiggy I hope you've not forgotten about us. We'd love to see the revised version of your Async patch!

**Comment by seiggy** [comment]
I haven't, I got sidetracked a bit. I'm planning on trying to get back to it this week or next and re-building the patch and submitting the pull request. We had some major shake-ups at the office around staffing, so it caused a couple weeks of madness to deal with :+1:

**Comment by skrusty** [comment]
@seiggy That's great news! Feel free to join us in #asternet on freenode (irc) if you want to chat about it.

**Pull request closed without merging**
