### PR TITLE
Changes to start working on .NET Core 1.0.1 support

### PR DESCRIPTION
**Pull request by seiggy**
This should be a compilable version that will work on Windows. I haven't tested Linux support yet, as I'll need to add that to the project.json.

I've swapped from RestSharp to FubarDevelopment.RestSharp as they have a fully PCL compliant version, and it looks like RestSharp is having some difficulties getting maintainers to merge the .NET Core pull requests that are available right now.

This also required an upgrade to Newtonsoft.Json 9 in order to support .NET Standard 1.6 PCL

Same with WebSocket4Net, the Core package relies on 0.15.0-beta6, but the ref is set at 0.15.0-\* so that when they hit final we won't need to change anything.

There's a couple things to get this to build locally:
1 - Private myget feed for the FubarDevelopment team is at: https://www.myget.org/F/restsharp-portable/api/v3/index.json
2 - Add the feed to your Nuget package manager settings in VS

I'm hoping the FubarDevelopment team will publish 4.0.1 to NuGet.com soon so that I can remove the reliance on their myget feed.

Migrated to NETStandard PCL version of RestSharp provided by https://github.com/FubarDevelopment/restsharp.portable
added precompiler flags for .NET Core
Removed ThreadPool Dispatcher if compiling on .NET Core (threadpool not
supported yet).

### CODE REVIEW

**Comment by seiggy** [comment]
There's a bug I'm working on fixing. Seems that the PCL RestSharp port changes the behavior around how Execute works. If you pass a full path like "/channels/" it won't go to "/ARI/channels" instead it goes to "/channels". So I'm working on fixing the T4 template to remove the leading "/" from the generated code to fix this behavior.

**Comment by seiggy** [comment]
Nope. The changes you'll see in the non-PCL code, are pre-compilation headers to allow it to use the correct Framework libs based on Net Standard / Full Framework compilation flags. That lets us continue to release the full .NET Framework 4.5 library without any changes for users, and add support for .NET Standard also without changes to the surface of the API.

**Comment by seiggy** [comment]
Yeah, I'm still having Travis ci issues too. We might have to wait for the
rest sharp fork to publish the package to the official feeds. I'm going to
keep trying to fix the build tonight some more though.

**Comment by seiggy** [comment]
What do you think about switching to AppVeyor instead of Travis CI?

**Comment by skrusty** [comment]
I'm open to suggestions. I did look at it to be honest, but only in passing. Tarvis-CI "seemed" to be a good choice at the time. That being said, it may not be the best option moving forwards.

What are the Pro's/Con's?

**Comment by seiggy** [comment]
Biggest pro is that it's much more .NET Friendly. Travis-CI runs on linux, so you have to use the mono builder, and then the .NET Core tooling on linux to build the linux binaries. Problem is that the mono-dev tools are kinda finiky. They aren't restoring the images from non-official repositories properly, even though the nuget.config file is there. Not sure why.

AppVeyor is a little more complicated to setup. Shouldn't take me but a couple hours to get the config setup right and get the appveyor.yml file created. But once that's there, it gives us all the same stuff that TravisCI does, plus it gives us NuGet Deployment automation. Which is a nice plus.

**Comment by seiggy** [comment]
success! I finally fixed Travis CI.

**Comment by skrusty** [comment]
Pld! What was it out of interest? I like the idea of having builds created by AppVeyor though! That does sound very handy...

**Comment by seiggy** [comment]
Since I was using .net core, I had to switch to using dotnet restore, as Travis CI uses NuGet 3.3.4 instead of 3.5, which is required for the new .NET Core framework references. So it was failing on the sln restore. So I created a project.json build file for the mono project, and completely swapped to using dotnet restore / dotnet build for the build script. Added the nuget.config to the root, and bam.

**Comment by seiggy** [comment]
I've also got a working AppVeyor build. We'll need to create a myget repo for deploying beta packages based on pull request for testing, and then setup the auto-deploy of the master branch to the nuget repo. But that's not too bad to setup.

**Comment by skrusty** [comment]
awesome work @seiggy! Let me know if you want me to do anything.

**Comment by skrusty** [comment]
What do we need to do to push this through to master?

I know there is a merge conflict, but apart from that, what else do we need to do in terms of builds for core vs .net 4.5.x
Cheers

**Comment by seiggy** [comment]
I think that's it. I'll see if I can pull and resolve the merge conflict this afternoon.

**Comment by seiggy** [comment]
@skrusty do you want me to modify the Travis build to pack and push the nuget package?

**Pull request merged**
