### PR TITLE
RunSynchronously exception on RESTActionConsumer.cs

### PR DESCRIPTION
**Pull request by alejogagliardi**
Hi, i have compiled branch master because i need to use OnPeerStatusCangeEvent, what is not present in NuGet package ver 1.1.0, and i had got an exception of "run synchronously may not be called on a task unbound to a delegate" on result.RunSynchronously perhaps due a synchronization context problem. I was able to solve the problem using result.GetAwaiter().GetResult();

Hope this help

Best regards

### CODE REVIEW

**Comment by skrusty** [comment]
HI, thanks for your contribution.

I am not the worlds best with async, so any ideas why GetResult() works and not RunSynchronously() ?

Cheers,
Ben

**Comment by alejogagliardi** [comment]
Hi, Ben, sorry for the delay on answer. It´s the first time i had used this method, Ithink the task may by wrapped within a Func delegate to bound the task to an delegate, i has don't try this yet. Another alternative it´s run the task directly with "Run" and call wait on this task,  I think you can ommit  the wait method because the "result.Result" call will block until "Result" becomes available.

**Comment by alejogagliardi** [comment]
Ben, I forgot to mention that if the task thrown an exception if you used  GetAwaiter.GetResult  you will get that exception otherwise, by calling Wait or Result you will have an AggregateException and you must inspect that in order to know what happened.

**Comment by skrusty** [comment]
Yes, I had read the same about the AggregateException. 

Cheers, Ben

**Pull request merged**
