### PR TITLE
Added new Async Events and supporting code.

### PR DESCRIPTION
**Pull request by seiggy**
Went back and re-created all my changes as discussed with new Async methods. Existing code should not be broken. I'm going to go through and re-create all the sample projects with Async code to show the changes in a demo as well.

### CODE REVIEW

**Comment by skrusty** [comment]
Cool! Thanks @seiggy will review this today, sorry missed you on irc.

**Comment by seiggy** [comment]
ok, samples are duped. I'll try and put them through their paces if I have a chance at work this week. But from working with my modified version that I built off my previous pull request, we shouldn't see any issues. Performance will probably look the same as the samples are pretty straight forward and simple. You'll really see the increase with a heavily concurrent app handling several hundred calls.

**Comment by skrusty** [comment]
Lovely, going to have a good play with this at the weekend. Thanks @seiggy - Sorry we keep missing you on IRC, GMT! :]

**Comment by skrusty** [comment]
Merged into PR #30

**Pull request closed without merging**
