### PR TITLE
fix fields serialization format in UpdateObject method

### PR DESCRIPTION
**Pull request by evgenknis**
One more attempt to fix fields serialization issue that was mentioned here:  https://github.com/skrusty/AsterNET.ARI/pull/61

I also found commit (https://github.com/skrusty/AsterNET.ARI/commit/32b06f09d5cdf23c998dbc5dcda1e82f55fbe8a2) 
where changes are to the generated code too. I`ve fixed it.

### CODE REVIEW

**Review by skrusty — COMMENTED** [review]
Looks good, I will pull this down tonight and test

**Comment by evgenknis** [comment]
Hello! I`ve faced this problem https://github.com/JamesNK/Newtonsoft.Json/issues/1998 when added variables to ARI channel request. So I've updated Newtonsoft.Json library to fix this. Also I`ve changed RestSharp.Portable to original RestSharp library, because RestSharp.Portable is no longer maintained and references old Newtonsoft library. Besides The Original RestSharp already supports .Net45 and .NetStandart. Also I adjusted frameworks in all projects to .net 4.5.2 and .netStandart 2.0

**Comment by skrusty** [comment]
Are you able to limit this PR to just the fix to the generator? It will make for a much cleaner PR to review.

**Comment by evgenknis** [comment]
> Are you able to limit this PR to just the fix to the generator? It will make for a much cleaner PR to review.

Hello. I did it

**Pull request closed without merging**
